/* 
 *
 * TinySHA1 - a header only implementation of the SHA1 algorithm. Based
 * on the implementation in boost::uuid::details
 * 
 * Copyright (c) 2012-22 SAURAV MOHAPATRA <mohaps@gmail.com>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */
 
#include "TinySHA1.h"
#include "TinySHA1Optim.h"
#include <iostream>
#include <string>

int compare(char a[],char b[]){
    for(int i=0;a[i]!='\0';i++){
        if(a[i]!=b[i])
            return 0;
    }
    return 1;
}

void testSHA1(const std::string& val) {
	plt::SHA1 s;
	s.processBytes(val.c_str(), val.size());
	uint32_t digest[5];
	s.getDigest(digest);	
	char tmp[48];
	snprintf(tmp, 45, "%08x %08x %08x %08x %08x", digest[0], digest[1], digest[2], digest[3], digest[4]);
	std::cout<<"Hashed Result of SHA1: "<<tmp<<std::endl;

	pltoptim::SHA1 ss;
	ss.processBytes(val.c_str(), val.size());
	uint32_t digestOpt[5];
	ss.getDigest(digestOpt);
	char tmpOpt[48];
	snprintf(tmpOpt, 45, "%08x %08x %08x %08x %08x", digestOpt[0], digestOpt[1], digestOpt[2], digestOpt[3], digestOpt[4]);
	std::cout<<"Hashed result of SHA1 Optimized: "<<tmpOpt<<std::endl;
	int result = compare(tmp, tmpOpt);
	result == 0 ? std::cout << "Failure!" << std::endl : std::cout << "Success!" << std::endl;
}

int main(int argc, char **argv) {
	
	 std::string str1 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ornare quam viverra orci sagittis. Id nibh tortor id aliquet lectus proin. Massa eget egestas purus viverra accumsan in nisl nisi. Pellentesque dignissim enim sit amet. Ullamcorper morbi tincidunt ornare massa eget egestas. Mauris pharetra et ultrices neque ornare aenean euismod elementum nisi. Cras semper auctor neque vitae. Interdum posuere lorem ipsum dolor sit amet consectetur. A condimentum vitae sapien pellentesque. Scelerisque fermentum dui faucibus in ornare quam. Convallis aenean et tortor at risus viverra adipiscing at. Blandit turpis cursus in hac habitasse platea. Amet mauris commodo quis imperdiet massa tincidunt. Sed arcu non odio euismod. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor.";
	testSHA1(str1);
        testSHA1("Tincidunt arcu non sodales neque sodales ut. Ridiculus mus mauris vitae ultricies leo. Diam vel quam elementum pulvinar etiam non. Mattis aliquam faucibus purus in massa tempor. Id interdum velit laoreet id. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque. Pretium vulputate sapien nec sagittis aliquam. Gravida cum sociis natoque penatibus et magnis. Risus pretium quam vulputate dignissim suspendisse. In hac habitasse platea dictumst quisque sagittis purus.");
        testSHA1("Mattis vulputate enim nulla aliquet. Tempus iaculis urna id volutpat lacus laoreet non. Augue ut lectus arcu bibendum at varius vel. Id faucibus nisl tincidunt eget. Consequat ac felis donec et odio pellentesque diam. Quis enim lobortis scelerisque fermentum dui faucibus in. In dictum non consectetur a erat nam at lectus urna. Lacus laoreet non curabitur gravida arcu ac tortor dignissim convallis. Nulla pharetra diam sit amet nisl suscipit adipiscing. Nec ullamcorper sit amet risus nullam. Amet nisl purus in mollis. Duis tristique sollicitudin nibh sit amet commodo nulla. Fusce id velit ut tortor. Fames ac turpis egestas maecenas pharetra convallis posuere morbi leo. Condimentum mattis pellentesque id nibh tortor id. Nullam eget felis eget nunc lobortis mattis. Dui sapien eget mi proin sed libero enim sed faucibus. Ut porttitor leo a diam sollicitudin tempor id. Tristique senectus et netus et malesuada.");
        testSHA1("Vitae auctor eu augue ut lectus arcu bibendum. Nulla facilisi morbi tempus iaculis urna. Sit amet consectetur adipiscing elit pellentesque habitant morbi tristique. Magna fringilla urna porttitor rhoncus dolor purus. At varius vel pharetra vel turpis nunc eget lorem. Gravida arcu ac tortor dignissim convallis aenean. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce. Fringilla phasellus faucibus scelerisque eleifend. Arcu non odio euismod lacinia at quis risus sed. In iaculis nunc sed augue. Donec et odio pellentesque diam volutpat commodo sed egestas. Convallis tellus id interdum velit laoreet. Et tortor at risus viverra. Laoreet id donec ultrices tincidunt arcu. Erat velit scelerisque in dictum non consectetur. Mattis rhoncus urna neque viverra justo nec ultrices dui sapien.");
        testSHA1("Ut lectus arcu bibendum at. Augue eget arcu dictum varius duis at consectetur lorem donec. Odio eu feugiat pretium nibh ipsum. Amet aliquam id diam maecenas ultricies mi. Dignissim enim sit amet venenatis. Mauris pharetra et ultrices neque ornare. Id consectetur purus ut faucibus pulvinar. Volutpat ac tincidunt vitae semper quis lectus nulla. Elementum sagittis vitae et leo duis ut diam quam nulla. Malesuada proin libero nunc consequat. Ut enim blandit volutpat maecenas volutpat. Ut pharetra sit amet aliquam id diam maecenas ultricies. Mattis molestie a iaculis at erat. Velit euismod in pellentesque massa. Suspendisse interdum consectetur libero id faucibus nisl tincidunt eget. Dui vivamus arcu felis bibendum ut tristique et. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at augue eget.");
        testSHA1("Suspendisse faucibus interdum posuere lorem ipsum. Et netus et malesuada fames ac turpis egestas sed. Nec dui nunc mattis enim ut. Elementum curabitur vitae nunc sed velit. Nisl pretium fusce id velit. Viverra vitae congue eu consequat ac felis donec et. Elementum integer enim neque volutpat ac. Egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Est ultricies integer quis auctor elit sed vulputate mi sit. Ac turpis egestas sed tempus urna et pharetra. Eros in cursus turpis massa tincidunt dui ut ornare. Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Molestie nunc non blandit massa enim nec dui nunc. Cras semper auctor neque vitae tempus quam pellentesque nec nam.");
 testSHA1("Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam. Eget felis eget nunc lobortis. Ut tellus elementum sagittis vitae. In dictum non consectetur a erat nam at lectus. Feugiat vivamus at augue eget arcu dictum varius duis at. Duis ut diam quam nulla porttitor massa. Faucibus ornare suspendisse sed nisi lacus sed. Viverra orci sagittis eu volutpat odio facilisis mauris sit amet. Tellus in hac habitasse platea dictumst vestibulum rhoncus. Adipiscing commodo elit at imperdiet dui. Mauris vitae ultricies leo integer malesuada nunc vel. Nunc congue nisi vitae suscipit tellus mauris a diam maecenas. Pharetra vel turpis nunc eget lorem dolor. Justo nec ultrices dui sapien eget. Blandit cursus risus at ultrices mi tempus imperdiet nulla malesuada. Vulputate eu scelerisque felis imperdiet proin fermentum. Et malesuada fames ac turpis egestas maecenas pharetra. In ornare quam viverra orci sagittis eu volutpat odio facilisis. Urna nunc id cursus metus aliquam eleifend mi in nulla. Sagittis eu volutpat odio facilisis mauris sit amet.");
        testSHA1("Sed faucibus turpis in eu mi bibendum neque egestas. Nisl suscipit adipiscing bibendum est ultricies integer. Dictum non consectetur a erat nam at. Nibh sed pulvinar proin gravida hendrerit. Diam phasellus vestibulum lorem sed risus ultricies tristique. Et netus et malesuada fames. Id diam vel quam elementum pulvinar etiam non quam lacus. Non nisi est sit amet facilisis magna etiam tempor. Nunc sed blandit libero volutpat. In ornare quam viverra orci sagittis eu volutpat. Hendrerit dolor magna eget est lorem ipsum dolor. Nulla posuere sollicitudin aliquam ultrices.");
        testSHA1("Ornare suspendisse sed nisi lacus. Nisl pretium fusce id velit ut tortor. Vel pretium lectus quam id leo in vitae turpis. Aliquet bibendum enim facilisis gravida neque convallis a. Laoreet suspendisse interdum consectetur libero. Vulputate ut pharetra sit amet aliquam id. Tempus egestas sed sed risus pretium quam vulputate dignissim. Egestas sed tempus urna et pharetra pharetra massa. Amet mattis vulputate enim nulla aliquet porttitor lacus. Tempus egestas sed sed risus pretium quam. Dui accumsan sit amet nulla facilisi. Mi bibendum neque egestas congue. Pretium nibh ipsum consequat nisl vel pretium. Eget mi proin sed libero enim sed. Integer eget aliquet nibh praesent tristique. Sit amet purus gravida quis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Libero id faucibus nisl tincidunt eget nullam non. Purus gravida quis blandit turpis cursus in hac habitasse platea.");
        testSHA1("Libero justo laoreet sit amet cursus sit amet dictum. Urna porttitor rhoncus dolor purus non enim praesent. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque. Dui ut ornare lectus sit amet est placerat in egestas. Amet mauris commodo quis imperdiet. At lectus urna duis convallis convallis tellus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque. Volutpat commodo sed egestas egestas fringilla. Libero volutpat sed cras ornare arcu. Adipiscing bibendum est ultricies integer quis auctor elit sed. Ornare aenean euismod elementum nisi quis eleifend quam. Amet luctus venenatis lectus magna. Faucibus interdum posuere lorem ipsum dolor sit amet.");
        testSHA1("Enim nunc faucibus a pellentesque sit amet. Libero enim sed faucibus turpis in. At erat pellentesque adipiscing commodo. Quisque non tellus orci ac auctor augue mauris augue neque. Ultricies tristique nulla aliquet enim tortor at auctor urna. Ac placerat vestibulum lectus mauris ultrices eros in cursus. Amet consectetur adipiscing elit ut aliquam purus sit. Mauris vitae ultricies leo integer malesuada nunc. Blandit cursus risus at ultrices mi tempus imperdiet nulla. Nulla facilisi nullam vehicula ipsum a. Facilisis magna etiam tempor orci eu lobortis elementum nibh tellus. Eget nunc lobortis mattis aliquam faucibus purus in massa. Dui sapien eget mi proin sed libero enim sed. Semper eget duis at tellus at urna condimentum. Non odio euismod lacinia at. Neque gravida in fermentum et sollicitudin ac orci phasellus egestas. Cras semper auctor neque vitae tempus quam pellentesque. Fringilla ut morbi tincidunt augue. Enim facilisis gravida neque convallis a. Nisi porta lorem mollis aliquam.");
        testSHA1("In est ante in nibh mauris cursus mattis. Tempor orci eu lobortis elementum nibh. Nulla facilisi morbi tempus iaculis urna id volutpat. Vitae turpis massa sed elementum tempus egestas sed sed risus. Ut tortor pretium viverra suspendisse potenti nullam. Amet consectetur adipiscing elit ut aliquam purus sit amet. Turpis egestas pretium aenean pharetra magna ac placerat vestibulum lectus. A scelerisque purus semper eget duis at tellus. In fermentum et sollicitudin ac orci phasellus egestas. Ac turpis egestas integer eget aliquet nibh. In eu mi bibendum neque. Nulla aliquet porttitor lacus luctus accumsan tortor posuere ac. Ac orci phasellus egestas tellus rutrum tellus pellentesque eu. Eget arcu dictum varius duis at consectetur lorem donec massa. Ipsum consequat nisl vel pretium lectus. Eu volutpat odio facilisis mauris sit amet. Tincidunt praesent semper feugiat nibh.");
        testSHA1("Enim ut tellus elementum sagittis vitae et leo duis ut. Orci ac auctor augue mauris augue neque gravida in. Mi tempus imperdiet nulla malesuada pellentesque elit eget. Nec dui nunc mattis enim ut tellus elementum sagittis. Non enim praesent elementum facilisis leo vel. Id neque aliquam vestibulum morbi blandit cursus. At quis risus sed vulputate. Urna neque viverra justo nec ultrices dui sapien eget mi. Sed nisi lacus sed viverra tellus in hac. Porttitor rhoncus dolor purus non enim. Tempor id eu nisl nunc mi ipsum faucibus vitae aliquet. Mauris sit amet massa vitae tortor condimentum lacinia. Feugiat in ante metus dictum at tempor commodo ullamcorper. Eu turpis egestas pretium aenean pharetra magna. Mattis nunc sed blandit libero.");
 testSHA1("Vestibulum sed arcu non odio euismod lacinia. Nec sagittis aliquam malesuada bibendum arcu vitae. Hendrerit dolor magna eget est lorem ipsum. Libero id faucibus nisl tincidunt eget nullam non. Enim sed faucibus turpis in eu mi bibendum. Lorem mollis aliquam ut porttitor leo. Convallis convallis tellus id interdum velit laoreet. Egestas pretium aenean pharetra magna. Id consectetur purus ut faucibus pulvinar elementum integer. Urna neque viverra justo nec ultrices dui sapien. Tempus urna et pharetra pharetra massa massa ultricies mi. Ut ornare lectus sit amet. Id diam vel quam elementum pulvinar etiam. Tristique senectus et netus et malesuada fames ac turpis.");
        testSHA1("Eros in cursus turpis massa tincidunt dui ut. Consectetur adipiscing elit pellentesque habitant morbi tristique senectus et. Dignissim cras tincidunt lobortis feugiat vivamus. Odio facilisis mauris sit amet massa vitae tortor condimentum lacinia. Lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant. Scelerisque viverra mauris in aliquam sem fringilla. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Donec adipiscing tristique risus nec. Fermentum leo vel orci porta non pulvinar neque laoreet. Sit amet nulla facilisi morbi tempus. Vitae tempus quam pellentesque nec nam aliquam. Aliquam nulla facilisi cras fermentum odio eu feugiat.");
        testSHA1("Diam maecenas ultricies mi eget. Pulvinar etiam non quam lacus suspendisse faucibus interdum posuere lorem. Dictum non consectetur a erat nam at. In mollis nunc sed id. Enim sit amet venenatis urna cursus eget nunc scelerisque viverra. Elementum eu facilisis sed odio morbi quis commodo. Gravida dictum fusce ut placerat orci nulla pellentesque dignissim. Bibendum at varius vel pharetra vel turpis nunc. Sed libero enim sed faucibus turpis. Egestas integer eget aliquet nibh praesent. Aliquet risus feugiat in ante metus dictum. Egestas purus viverra accumsan in nisl nisi scelerisque eu ultrices. Ultricies mi quis hendrerit dolor magna eget est lorem. Euismod elementum nisi quis eleifend quam. Purus sit amet luctus venenatis lectus magna fringilla. Commodo odio aenean sed adipiscing diam donec adipiscing tristique. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus et.");
        testSHA1("Blandit cursus risus at ultrices. Sit amet consectetur adipiscing elit ut aliquam. Pellentesque elit eget gravida cum sociis natoque penatibus et magnis. Augue mauris augue neque gravida in. Mattis nunc sed blandit libero volutpat sed. Eget magna fermentum iaculis eu non diam phasellus vestibulum. Sit amet risus nullam eget felis eget. Tincidunt augue interdum velit euismod in pellentesque. Nam at lectus urna duis convallis convallis tellus id. Magna sit amet purus gravida.Proin libero nunc consequat interdum varius sit amet. Quam vulputate dignissim suspendisse in. Non consectetur a erat nam at lectus urna duis. Aliquet nibh praesent tristique magna sit. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Nibh tortor id aliquet lectus proin nibh nisl condimentum id. At elementum eu facilisis sed odio. Rhoncus dolor purus non enim praesent elementum facilisis leo. Praesent elementum facilisis leo vel fringilla est ullamcorper eget. Quis imperdiet massa tincidunt nunc pulvinar.");
        testSHA1("Sit amet mattis vulputate enim nulla aliquet. Amet est placerat in egestas erat imperdiet sed euismod. Cras fermentum odio eu feugiat pretium nibh ipsum. Risus pretium quam vulputate dignissim. Aliquet bibendum enim facilisis gravida neque convallis a cras. In tellus integer feugiat scelerisque varius. Suspendisse ultrices gravida dictum fusce ut placerat orci nulla pellentesque. Proin gravida hendrerit lectus a. Amet massa vitae tortor condimentum lacinia quis. Faucibus a pellentesque sit amet. Felis bibendum ut tristique et egestas quis ipsum suspendisse. Justo nec ultrices dui sapien eget mi proin sed libero. Magna ac placerat vestibulum lectus mauris ultrices. Est sit amet facilisis magna. Sed turpis tincidunt id aliquet risus feugiat in ante metus. Mauris sit amet massa vitae tortor. Netus et malesuada fames ac turpis egestas maecenas pharetra. Pretium aenean pharetra magna ac placerat. Aenean euismod elementum nisi quis eleifend quam. Lorem mollis aliquam ut porttitor leo a.");
        testSHA1("Est pellentesque elit ullamcorper dignissim cras. Ac felis donec et odio pellentesque diam volutpat commodo sed. Posuere ac ut consequat semper. Ultrices dui sapien eget mi proin sed libero. At ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget. Amet facilisis magna etiam tempor. In cursus turpis massa tincidunt dui ut ornare lectus. Nulla at volutpat diam ut venenatis tellus in metus vulputate. Aliquet bibendum enim facilisis gravida neque convallis. Blandit turpis cursus in hac. Sit amet est placerat in egestas erat imperdiet. Tempor id eu nisl nunc mi ipsum faucibus. Neque viverra justo nec ultrices dui sapien. Nulla facilisi etiam dignissim diam quis. Tellus elementum sagittis vitae et leo duis ut diam quam. Mauris sit amet massa vitae tortor condimentum. Volutpat est velit egestas dui id ornare arcu.");
 testSHA1("Semper feugiat nibh sed pulvinar proin gravida hendrerit lectus. Viverra justo nec ultrices dui sapien eget mi. Ornare massa eget egestas purus viverra. Leo in vitae turpis massa sed elementum tempus egestas. Ultricies tristique nulla aliquet enim tortor at auctor urna. Turpis in eu mi bibendum. Nunc lobortis mattis aliquam faucibus. Mi quis hendrerit dolor magna eget est lorem. Nec feugiat in fermentum posuere urna nec tincidunt. Dignissim diam quis enim lobortis scelerisque fermentum dui faucibus. Etiam tempor orci eu lobortis elementum nibh tellus. Cursus turpis massa tincidunt dui. Sed risus ultricies tristique nulla aliquet enim tortor. At varius vel pharetra vel turpis nunc eget. Imperdiet nulla malesuada pellentesque elit eget gravida cum sociis. Ut tellus elementum sagittis vitae et leo duis ut diam. Viverra orci sagittis eu volutpat odio facilisis mauris. Dictum non consectetur a erat nam. Faucibus turpis in eu mi bibendum neque.");
        testSHA1("Dolor sed viverra ipsum nunc aliquet bibendum enim. Ultricies mi eget mauris pharetra et ultrices. Dolor sed viverra ipsum nunc. In mollis nunc sed id semper risus in hendrerit. Gravida dictum fusce ut placerat orci. Nunc aliquet bibendum enim facilisis gravida neque convallis a cras. Lectus nulla at volutpat diam. Congue mauris rhoncus aenean vel elit. Arcu risus quis varius quam quisque id diam. Vivamus arcu felis bibendum ut tristique et. Tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras.Tellus mauris a diam maecenas sed enim ut sem viverra. Quis hendrerit dolor magna eget. Aenean euismod elementum nisi quis eleifend quam adipiscing. Mauris augue neque gravida in fermentum et. Et ultrices neque ornare aenean euismod elementum nisi quis. Feugiat in fermentum posuere urna nec tincidunt praesent. Tristique senectus et netus et. Ornare massa eget egestas purus viverra accumsan. Pulvinar pellentesque habitant morbi tristique senectus et. Fringilla ut morbi tincidunt augue interdum velit. Vitae justo eget magna fermentum iaculis. Congue nisi vitae suscipit tellus mauris a diam maecenas sed.");
        testSHA1("Egestas purus viverra accumsan in nisl nisi scelerisque eu. Convallis posuere morbi leo urna molestie. In dictum non consectetur a erat nam at lectus. Non tellus orci ac auctor augue mauris augue neque gravida. Bibendum arcu vitae elementum curabitur vitae nunc sed velit dignissim. Diam maecenas sed enim ut sem viverra. Dignissim cras tincidunt lobortis feugiat. Egestas erat imperdiet sed euismod nisi porta lorem. Quam elementum pulvinar etiam non quam lacus. Nisl vel pretium lectus quam id leo in vitae turpis. Diam vulputate ut pharetra sit. Ut tortor pretium viverra suspendisse potenti. A erat nam at lectus urna. Maecenas accumsan lacus vel facilisis volutpat est velit egestas. Eu non diam phasellus vestibulum. Ultricies lacus sed turpis tincidunt id aliquet risus feugiat in. Ut sem nulla pharetra diam sit amet nisl. Dictum varius duis at consectetur lorem donec massa sapien faucibus. Ultricies mi eget mauris pharetra et ultrices neque.");
        testSHA1("Egestas purus viverra accumsan in nisl nisi scelerisque eu. Convallis posuere morbi leo urna molestie. In dictum non consectetur a erat nam at lectus. Non tellus orci ac auctor augue mauris augue neque gravida. Bibendum arcu vitae elementum curabitur vitae nunc sed velit dignissim. Diam maecenas sed enim ut sem viverra. Dignissim cras tincidunt lobortis feugiat. Egestas erat imperdiet sed euismod nisi porta lorem. Quam elementum pulvinar etiam non quam lacus. Nisl vel pretium lectus quam id leo in vitae turpis. Diam vulputate ut pharetra sit. Ut tortor pretium viverra suspendisse potenti. A erat nam at lectus urna. Maecenas accumsan lacus vel facilisis volutpat est velit egestas. Eu non diam phasellus vestibulum. Ultricies lacus sed turpis tincidunt id aliquet risus feugiat in. Ut sem nulla pharetra diam sit amet nisl. Dictum varius duis at consectetur lorem donec massa sapien faucibus. Ultricies mi eget mauris pharetra et ultrices neque.");
        testSHA1("Dolor magna eget est lorem ipsum dolor. Feugiat in ante metus dictum at tempor commodo ullamcorper a. Sapien nec sagittis aliquam malesuada bibendum. Congue eu consequat ac felis. Adipiscing elit duis tristique sollicitudin nibh sit amet. At tellus at urna condimentum mattis. Risus in hendrerit gravida rutrum quisque non tellus. Euismod elementum nisi quis eleifend. A scelerisque purus semper eget duis at tellus. Elit pellentesque habitant morbi tristique senectus et netus et malesuada. Felis bibendum ut tristique et egestas quis. Sagittis aliquam malesuada bibendum arcu. Sit amet nulla facilisi morbi tempus iaculis urna.Parturient montes nascetur ridiculus mus mauris. Magnis dis parturient montes nascetur ridiculus mus mauris vitae. Tincidunt augue interdum velit euismod in. Eu nisl nunc mi ipsum faucibus vitae aliquet nec. Vitae turpis massa sed elementum tempus egestas sed sed risus. Nisl purus in mollis nunc. At tempor commodo ullamcorper a lacus vestibulum. Dignissim suspendisse in est ante. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit. Sit amet dictum sit amet justo donec. Scelerisque felis imperdiet proin fermentum leo vel orci porta. Id aliquet risus feugiat in ante. In vitae turpis massa sed. Morbi blandit cursus risus at.");
        testSHA1("Tincidunt arcu non sodales neque sodales. Risus pretium quam vulputate dignissim. Varius quam quisque id diam vel quam elementum pulvinar. Habitasse platea dictumst quisque sagittis purus. Aliquam purus sit amet luctus venenatis lectus magna. Sit amet aliquam id diam. Libero id faucibus nisl tincidunt eget nullam non. Sed id semper risus in hendrerit gravida rutrum. Adipiscing commodo elit at imperdiet dui. Libero id faucibus nisl tincidunt eget. Et malesuada fames ac turpis egestas sed tempus urna. Amet mattis vulputate enim nulla aliquet. Volutpat maecenas volutpat blandit aliquam etiam erat velit scelerisque. Purus faucibus ornare suspendisse sed nisi lacus sed viverra. Morbi leo urna molestie at elementum eu facilisis sed. Tincidunt dui ut ornare lectus sit amet est. Amet justo donec enim diam. Magna sit amet purus gravida quis.");
testSHA1("Urna molestie at elementum eu. A erat nam at lectus urna duis convallis convallis tellus. Scelerisque purus semper eget duis at tellus. Imperdiet proin fermentum leo vel. Volutpat consequat mauris nunc congue nisi vitae suscipit. Pellentesque habitant morbi tristique senectus et netus et malesuada. Urna nec tincidunt praesent semper feugiat. Dignissim diam quis enim lobortis. Non consectetur a erat nam at lectus. Varius morbi enim nunc faucibus a pellentesque sit amet porttitor. Amet consectetur adipiscing elit ut aliquam. Aenean et tortor at risus viverra adipiscing at. Leo integer malesuada nunc vel risus commodo. Tristique magna sit amet purus. Vel pretium lectus quam id leo.");
        testSHA1("Urna neque viverra justo nec ultrices dui sapien eget. Tellus id interdum velit laoreet id donec ultrices tincidunt. Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Duis at tellus at urna condimentum mattis. Mauris nunc congue nisi vitae suscipit. Ultricies tristique nulla aliquet enim tortor at auctor urna. Amet massa vitae tortor condimentum lacinia quis vel eros. Auctor urna nunc id cursus metus aliquam. Enim facilisis gravida neque convallis a cras semper auctor. Semper quis lectus nulla at. Mattis rhoncus urna neque viverra. Amet commodo nulla facilisi nullam vehicula ipsum a. Ultrices neque ornare aenean euismod elementum nisi. Molestie ac feugiat sed lectus. Velit aliquet sagittis id consectetur purus. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar.");
        testSHA1("Volutpat maecenas volutpat blandit aliquam etiam erat velit scelerisque in. Enim praesent elementum facilisis leo vel fringilla. Porttitor rhoncus dolor purus non. Sed libero enim sed faucibus turpis. Purus ut faucibus pulvinar elementum integer enim neque volutpat. Cursus metus aliquam eleifend mi in nulla posuere. Massa enim nec dui nunc mattis enim ut tellus. Amet massa vitae tortor condimentum lacinia. Est placerat in egestas erat imperdiet sed euismod nisi porta. Adipiscing commodo elit at imperdiet dui accumsan. Quis varius quam quisque id diam vel quam elementum. Sed velit dignissim sodales ut. Elementum tempus egestas sed sed risus pretium. Eu non diam phasellus vestibulum lorem sed. Sit amet cursus sit amet dictum sit amet justo.Amet luctus venenatis lectus magna fringilla. Porttitor lacus luctus accumsan tortor posuere ac ut. Nullam vehicula ipsum a arcu cursus vitae congue mauris. Vel pretium lectus quam id leo in. Scelerisque fermentum dui faucibus in. Egestas tellus rutrum tellus pellentesque eu tincidunt. Sagittis id consectetur purus ut faucibus pulvinar elementum. Ac ut consequat semper viverra nam libero justo laoreet. Dolor morbi non arcu risus quis varius quam quisque id. Sit amet aliquam id diam maecenas. Laoreet suspendisse interdum consectetur libero id faucibus nisl. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Integer quis auctor elit sed vulputate mi sit amet. Tortor at risus viverra adipiscing at in tellus integer feugiat. Pulvinar neque laoreet suspendisse interdum consectetur libero id faucibus nisl. Pellentesque diam volutpat commodo sed. Placerat in egestas erat imperdiet.");
        testSHA1("Cum sociis natoque penatibus et magnis dis parturient. Lorem dolor sed viverra ipsum nunc aliquet. Sed libero enim sed faucibus turpis in. Mauris pharetra et ultrices neque. Aliquam purus sit amet luctus venenatis. Orci nulla pellentesque dignissim enim sit amet. Interdum varius sit amet mattis vulputate enim nulla aliquet porttitor. Varius quam quisque id diam. Nisl rhoncus mattis rhoncus urna neque viverra justo nec. Libero volutpat sed cras ornare arcu dui vivamus. Ut placerat orci nulla pellentesque dignissim. Elementum tempus egestas sed sed risus pretium quam. Sociis natoque penatibus et magnis dis parturient montes nascetur. Scelerisque varius morbi enim nunc faucibus.Volutpat diam ut venenatis tellus in metus. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Amet commodo nulla facilisi nullam vehicula ipsum. Ac ut consequat semper viverra nam libero justo laoreet sit. Aliquet enim tortor at auctor urna nunc id. Scelerisque varius morbi enim nunc faucibus a pellentesque sit. Id diam vel quam elementum pulvinar etiam. Est sit amet facilisis magna. Arcu risus quis varius quam quisque id diam vel. Sapien faucibus et molestie ac feugiat. Vulputate dignissim suspendisse in est. Elementum pulvinar etiam non quam lacus suspendisse.");
        testSHA1("Suspendisse in est ante in nibh mauris. Non consectetur a erat nam at lectus urna. Duis convallis convallis tellus id interdum. Ultrices neque ornare aenean euismod elementum nisi quis. Curabitur gravida arcu ac tortor dignissim convallis aenean et. Cursus sit amet dictum sit amet. Eu lobortis elementum nibh tellus molestie nunc. Porta lorem mollis aliquam ut. Ultrices eros in cursus turpis massa tincidunt dui ut ornare. Faucibus vitae aliquet nec ullamcorper sit amet risus. Magna etiam tempor orci eu lobortis elementum nibh tellus molestie. Ultricies mi quis hendrerit dolor magna eget est. Vivamus at augue eget arcu dictum varius duis. Bibendum ut tristique et egestas quis ipsum suspendisse. Amet risus nullam eget felis eget. Non curabitur gravida arcu ac tortor dignissim convallis aenean et. Mattis rhoncus urna neque viverra justo nec ultrices. Eleifend donec pretium vulputate sapien nec. Id interdum velit laoreet id.");
        testSHA1("Nulla facilisi cras fermentum odio. Cursus vitae congue mauris rhoncus aenean vel elit scelerisque. Amet porttitor eget dolor morbi non arcu risus. Ridiculus mus mauris vitae ultricies leo integer malesuada. Nibh ipsum consequat nisl vel. Pulvinar etiam non quam lacus suspendisse faucibus. Fringilla ut morbi tincidunt augue interdum velit euismod in pellentesque. Eget duis at tellus at urna condimentum mattis. Bibendum neque egestas congue quisque egestas. Vestibulum morbi blandit cursus risus at ultrices mi tempus. Fames ac turpis egestas integer eget aliquet nibh. Sed arcu non odio euismod lacinia at quis risus. Commodo ullamcorper a lacus vestibulum sed arcu non. Cursus euismod quis viverra nibh cras pulvinar mattis nunc sed. Tellus integer feugiat scelerisque varius morbi enim nunc faucibus. Magnis dis parturient montes nascetur ridiculus.");
	testSHA1("");
	return 0;
}
